apiVersion: v1
kind: Config
clusters:
- name: my-aks-cluster
  cluster:
    server: https://your-aks-cluster-api-server
    certificate-authority-data: <your-certificate-authority-data>
contexts:
- name: my-aks-context
  context:
    cluster: my-aks-cluster
    user: my-aks-user
current-context: my-aks-context
users:
- name: my-aks-user
  user:
    client-certificate-data: <your-client-certificate-data>
    client-key-data: <your-client-key-data>
